/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueueIdIndexImport } from './routes/$queueId/index'
import { Route as QueueIdJobIdJobImport } from './routes/$queueId/$jobId/_job'
import { Route as QueueIdJobIdJobIndexImport } from './routes/$queueId/$jobId/_job.index'
import { Route as QueueIdJobIdJobTaskIdIndexImport } from './routes/$queueId/$jobId/_job.$taskId/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const QueueIdJobIdImport = createFileRoute('/$queueId/$jobId')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QueueIdJobIdRoute = QueueIdJobIdImport.update({
  path: '/$queueId/$jobId',
  getParentRoute: () => rootRoute,
} as any)

const QueueIdIndexRoute = QueueIdIndexImport.update({
  path: '/$queueId/',
  getParentRoute: () => rootRoute,
} as any)

const QueueIdJobIdJobRoute = QueueIdJobIdJobImport.update({
  id: '/_job',
  getParentRoute: () => QueueIdJobIdRoute,
} as any)

const QueueIdJobIdJobIndexRoute = QueueIdJobIdJobIndexImport.update({
  path: '/',
  getParentRoute: () => QueueIdJobIdJobRoute,
} as any)

const QueueIdJobIdJobTaskIdIndexRoute = QueueIdJobIdJobTaskIdIndexImport.update(
  {
    path: '/$taskId/',
    getParentRoute: () => QueueIdJobIdJobRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/$queueId/': {
      id: '/$queueId/'
      path: '/$queueId'
      fullPath: '/$queueId'
      preLoaderRoute: typeof QueueIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/$queueId/$jobId': {
      id: '/$queueId/$jobId'
      path: '/$queueId/$jobId'
      fullPath: '/$queueId/$jobId'
      preLoaderRoute: typeof QueueIdJobIdImport
      parentRoute: typeof rootRoute
    }
    '/$queueId/$jobId/_job': {
      id: '/$queueId/$jobId/_job'
      path: '/$queueId/$jobId'
      fullPath: '/$queueId/$jobId'
      preLoaderRoute: typeof QueueIdJobIdJobImport
      parentRoute: typeof QueueIdJobIdRoute
    }
    '/$queueId/$jobId/_job/': {
      id: '/$queueId/$jobId/_job/'
      path: '/'
      fullPath: '/$queueId/$jobId/'
      preLoaderRoute: typeof QueueIdJobIdJobIndexImport
      parentRoute: typeof QueueIdJobIdJobImport
    }
    '/$queueId/$jobId/_job/$taskId/': {
      id: '/$queueId/$jobId/_job/$taskId/'
      path: '/$taskId'
      fullPath: '/$queueId/$jobId/$taskId'
      preLoaderRoute: typeof QueueIdJobIdJobTaskIdIndexImport
      parentRoute: typeof QueueIdJobIdJobImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  QueueIdIndexRoute,
  QueueIdJobIdRoute: QueueIdJobIdRoute.addChildren({
    QueueIdJobIdJobRoute: QueueIdJobIdJobRoute.addChildren({
      QueueIdJobIdJobIndexRoute,
      QueueIdJobIdJobTaskIdIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/$queueId/",
        "/$queueId/$jobId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/$queueId/": {
      "filePath": "$queueId/index.tsx"
    },
    "/$queueId/$jobId": {
      "filePath": "$queueId/$jobId",
      "children": [
        "/$queueId/$jobId/_job"
      ]
    },
    "/$queueId/$jobId/_job": {
      "filePath": "$queueId/$jobId/_job.tsx",
      "parent": "/$queueId/$jobId",
      "children": [
        "/$queueId/$jobId/_job/",
        "/$queueId/$jobId/_job/$taskId/"
      ]
    },
    "/$queueId/$jobId/_job/": {
      "filePath": "$queueId/$jobId/_job.index.tsx",
      "parent": "/$queueId/$jobId/_job"
    },
    "/$queueId/$jobId/_job/$taskId/": {
      "filePath": "$queueId/$jobId/_job.$taskId/index.tsx",
      "parent": "/$queueId/$jobId/_job"
    }
  }
}
ROUTE_MANIFEST_END */
